# Generated by Django 3.2 on 2021-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210501_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasma',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
