# Generated by Django 3.2 on 2021-05-01 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210501_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(blank=True, choices=[('Remdesivir', 'Remdesivir'), ('Fabiflu', 'Fabiflu'), ('Medrol', 'Medrol'), ('Ivermectin', 'Ivermectin'), ('Doxycycline', 'Doxycycline')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 20, 54, 25, 755568)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 1, 20, 54, 25, 756606)),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 20, 54, 25, 755568)),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 20, 54, 25, 756606)),
        ),
    ]
