# Generated by Django 3.2 on 2021-05-01 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210501_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 21, 18, 28, 746320)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 1, 21, 18, 28, 748775)),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 21, 18, 28, 744326)),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 21, 18, 28, 747317)),
        ),
    ]
