# Generated by Django 3.2 on 2021-05-01 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210501_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasma',
            name='address',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 25, 26, 326796)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 1, 22, 25, 26, 334397)),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 25, 26, 326796)),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 25, 26, 326796)),
        ),
    ]
